services:
  - type: web
    name: game-app-backend
    env: java
    buildCommand: "cd backend && mvn package"
    startCommand: "java -jar backend/target/gameapprs.jar"
    envVars:
      - key: JAVA_VERSION
        value: "19"

  - type: web
    name: game-app-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npx serve -s frontend/build"
    envVars:
      - key: NODE_VERSION
        value: "16"
