services:
  - type: web
    name: game-app-backend
    env: docker
    dockerfilePath: ./Dockerfile

  - type: web
    name: game-app-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "n
